#!/usr/bin/python
import sys
import os
import threading
from SimpleHTTPServer import SimpleHTTPRequestHandler
from BaseHTTPServer import HTTPServer
import time
import webbrowser

DIR = os.path.dirname(__file__)
DOC_DIR = os.path.join(DIR, "docs", "html")
os.chdir(DOC_DIR)

server = HTTPServer(('', 8000), SimpleHTTPRequestHandler)
thread = threading.Thread(target = server.serve_forever)
thread.setdaemon = True
try:
    thread.start()
except KeyboardInterrupt:
    server.shutdown()
    sys.exit(0)

try:
    print 'Serving documentation on http://localhost:8000'
    webbrowser.open("http://localhost:8000")
    while True:
        time.sleep(1)
except:
    print
    print "Shutting documentation server down!"
    server.shutdown()
    thread.join()
    sys.exit(0)
