load("//bazel:fetchai_build_system.bzl", "fetchai_cc_library")


fetchai_cc_library(
  name = "version",
  srcs = glob(["src/*.cpp", 'bazel/*.cpp']),
  hdrs = glob(["include/*.hpp", "include/**/*.hpp"]),
)