#!/bin/bash
cd $(dirname "${BASH_SOURCE[0]}")

flex tokeniser.l


prepend_pragma="#pragma once"

prepend_this="//------------------------------------------------------------------------------\n"\
"//\n"\
"//   Copyright 2018-2019 Fetch.AI Limited\n"\
"//\n"\
"//   Licensed under the Apache License, Version 2.0 (the \"License\");\n"\
"//   you may not use this file except in compliance with the License.\n"\
"//   You may obtain a copy of the License at\n"\
"//\n"\
"//       http://www.apache.org/licenses/LICENSE-2.0\n"\
"//\n"\
"//   Unless required by applicable law or agreed to in writing, software\n"\
"//   distributed under the License is distributed on an \"AS IS\" BASIS,\n"\
"//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"\
"//   See the License for the specific language governing permissions and\n"\
"//   limitations under the License.\n"\
"//\n"\
"//------------------------------------------------------------------------------\n"\
"\n"\
"// clang-format off\n"

append_this="// clang-format on"

echo -e "$prepend_pragma\\n$prepend_this" | cat - ../include/vm/tokeniser.hpp > temp && mv temp ../include/vm/tokeniser.hpp
echo -e "$prepend_this" | cat - ../src/tokeniser.cpp > temp && mv temp ../src/tokeniser.cpp

echo -e "$append_this" >> ../include/vm/tokeniser.hpp
echo -e "$append_this" >> ../src/tokeniser.cpp
