#!/usr/bin/env python3
import os
import argparse
import fnmatch
import subprocess

SOURCE_FOLDERS = ('apps', 'libs')
SOURCE_EXT = ('*.cpp', '*.hpp')

def parse_commandline():
    parser = argparse.ArgumentParser()
    parser.add_argument('-w', '--warn-only', dest='fix', action='store_false', help='Only display warnings')
    return parser.parse_args()

def main():
    project_root = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))

    args = parse_commandline()

    print('Applying style...')

    cmd_prefix = [
        'clang-format',
        '-style=file',
    ]

    if args.fix:
        cmd_prefix += ['-i']


    for path in SOURCE_FOLDERS:
        for root, _, files in os.walk(os.path.join(project_root, path)):
            for ext in SOURCE_EXT:
                for file in fnmatch.filter(files, ext):
                    source_path = os.path.join(root, file)

                    # apply twice to allow the changes to "settle"
                    for _ in range(2):
                        subprocess.check_call(cmd_prefix + [source_path], cwd=project_root)


    print('Applying style...complete')


if __name__ == '__main__':
    main()
