#pragma once
//------------------------------------------------------------------------------
//
//   Copyright 2018-2019 Fetch.AI Limited
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//
//------------------------------------------------------------------------------

#include "core/byte_array/const_byte_array.hpp"

#include <array>

namespace fetch {
namespace crypto {
class Identity;
}

namespace ledger {
namespace v2 {

/**
 * The Address is a unifying mechanism between multiple different public keys types into a single
 * format.
 *
 * It is generated by creating a hash of the raw bytes of the public key. In addition, when
 * displaying the address on interfaces an additional 4 bytes of checksum is appended to the
 * address. This checksum is calculated by hashing the address and selecting the first 4 bytes of
 * the digest. This mechanism is common place and allows interfaces to integrity check the address.
 *
 * ┌──────────────────────────────────────────────────┐
 * │                    Public Key                    │
 * └──────────────────────────────────────────────────┘
 *                           │
 *                           │
 *                   Hashed (SHA-256)
 *                           │
 *                           │
 *                           ▼
 *                ┌─────────────────────┐
 *                │       Address       │ ───────────┐
 *                └─────────────────────┘            │
 *                           │                       │
 *                           │                       │
 *                    When Displaying              1st 4
 *                           │                    bytes of
 *                           │                      the
 *                           ▼                       │
 *            ┌─────────────────────┬────────┐       │
 *            │       Address       │Checksum│ ◀─────┘
 *            └─────────────────────┴────────┘
 *
 */
class Address
{
public:
  using RawAddress     = std::array<uint8_t, 32>;
  using ConstByteArray = byte_array::ConstByteArray;

  // Construction / Destruction
  Address() = default;
  explicit Address(crypto::Identity const &identity);
  explicit Address(RawAddress const &address);
  Address(Address const &) = default;
  Address(Address &&)      = default;
  ~Address()               = default;

  /// @name Accessors
  /// @{
  ConstByteArray address() const;
  ConstByteArray display() const;
  /// @}

  // Operators
  bool operator==(Address const &other) const;
  bool operator!=(Address const &other) const;

  Address &operator=(Address const &) = default;
  Address &operator=(Address &&) = default;

private:
  ConstByteArray address_;  ///< The address representation
  ConstByteArray display_;  ///< The display representation
};

/**
 * Get the raw bytes of the address
 *
 * @return The raw address
 */
inline Address::ConstByteArray Address::address() const
{
  return address_;
}

/**
 * Get the raw bytes of the display variant of the address (with checksum)
 *
 * @return The display address
 */
inline Address::ConstByteArray Address::display() const
{
  return display_;
}

/**
 * Equality operator for the address
 *
 * @param other The other address to compare against
 * @return true if equal, otherwise false
 */
inline bool Address::operator==(Address const &other) const
{
  return address_ == other.address_;
}

/**
 * Inequality operator for the address
 *
 * @param other The other address to compare against
 * @return true if NOT equal, otherwise false
 */
inline bool Address::operator!=(Address const &other) const
{
  return !(*this == other);
}

}  // namespace v2
}  // namespace ledger
}  // namespace fetch
